### ISSUE TITLE
Compatibility with App Store version of OF

### ISSUE THREAD

**Issue by jonasoesch** [jyruzicka/rubyfocus#1]
In `local_fetcher.rb` the path to the OF database is hardcoded. It doesn't work with the App Store Version where the path is

`File.join(ENV["HOME"], "/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Application Support/OmniFocus/OmniFocus.ofocus")
`

Could include that as a fallback in case the other DB isn't found.

**Comment by jyruzicka** [comment]
Should be fixed with 0.5.4

**Comment by jonasoesch** [comment]
Great. Thanks a lot!
