### ISSUE TITLE
Connecting to the Sync Server fails with "OmniFocus.ofocus: none found"

### ISSUE THREAD

**Issue by randomsnowflake** [jyruzicka/rubyfocus#18]
I need help to connect to the Sync Server.

I use the following code:
```
  f = Rubyfocus::OSSFetcher.new(USER, PASSWORD)
  d = Rubyfocus::Document.new(f)
```

And it fails with the following error:
```
/Users/user/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/rubyfocus-0.6.0/lib/rubyfocus/fetchers/oss_fetcher.rb:34:in `base': Looking for zip files at https://sync.omnigroup.com/ACCNAME/OmniFocus.ofocus: none found. (Rubyfocus::OSSFetcherError)
	from /Users/user/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/rubyfocus-0.6.0/lib/rubyfocus/document.rb:38:in `initialize'
	from rubyofcus.rb:21:in `new'
	from rubyofcus.rb:21:in `<main>'
```

This happens no matter if I use the account name or the account E-mail. Omnifocus itself is connected to the server, so the fault is at my end.

Thanks for advice how to fix this.

**Comment by jyruzicka** [comment]
Sorry, it's been ages since I've even tried to use this to connect to the sync server (at least four years). It's entirely possible that OmniFocus have changed how they store their data on the server, or it could be due to encryption on their end.

Sorry I can't be of more help.
