### ISSUE TITLE
db.yaml project status active instead of dropped

### ISSUE THREAD

**Issue by Kondamon** [jyruzicka/rubyfocus#3]
I have noticed that db.yaml has sometimes wrong status entries for projects. For example one project was dropped in omnifocus but in db.yaml the status was still inactive. After running omniboard with reset nothing changes.
The issue can be resolved by changing the project status in omnifocus back to active and the switch to dropped again. After that the status entry for the relevant project in db.yaml is also "dropped".

The same wrong status was noticed also for other projects within db.yaml. Do you know what could be the issue?

**Comment by jyruzicka** [comment]
Hi @Kondamon! The most likely culprit is OmniGroup's versioning system that it uses to enable syncing between devices. It basically stores data as a base file plus a series of "diffs" (i.e. "to get from the base database to version 54212 of the database, delete this project, and mark these three tasks as done..."). The current omniboard/rubyfocus does a good job of navigating the diff "tree", but can get stuck up a blind alley.

In most instances, syncing all your devices should fix this. I know it's not the best solution: when I have some spare time, I might get around to re-coding the tree navigation stuff, so it doesn't get caught like this.

Let me know if syncing other devices fixes this issue.

**Comment by Kondamon** [comment]
Ok, thank you for your advice. I'll try out the next time if it works this way. Usually the sync should be initiated automatically to all other devices.
